### ISSUE TITLE
How VILA can handle 8 frames from videos?

### ISSUE THREAD

**Issue by KangsanKim07** [NVlabs/VILA#83]
Hi, thanks for sharing great work!
I noticed VILA uses 8 frames for video,
but if image token is 576 then the token length of 8 frames will be 4608 (576*8) which is over than 'model_max_length'(4096).
It seems all VILA models except LLaMA3-8B one have max length as 4096.
Could you explain how these models can accept 8 frames of video, please?

**Comment by yaolug** [comment]
First we use siglip/internvit that will be 729/1024 tokens per image.
Second, see section 4.4 of our paper https://arxiv.org/pdf/2312.07533 we reshape a 2x2 patch into 1 token to reduce the # of tokens by 4x. Code is here: https://github.com/NVlabs/VILA/blob/main/llava/model/multimodal_projector/base_projector.py#L33

**Comment by KangsanKim07** [comment]
Thanks for answering!
Now I clearly understood it :)

**Comment by alphadadajuju** [comment]
Hi, 

Following your previous discussion about how VILA handles 8 frames, I am still a bit confused. 

Let's say if a maximum of 1024 tokens are extracted from a single frame, followed by a reduction of 4 times (i.e., 256 tokens) thanks to the technique introduced in section 4.4, then wouldn't 4096 (model_max_length) / 256 = 16, meaning that VILA can handle 16 frames (instead of 8)?

Thanks again for sharing such an amazing work!

**Comment by yaolug** [comment]
You need some tokens for question and answer. So 16 won't work. In theory you can try 14 frames. But for simplicity, we just train w/ 8 frames.

**Comment by alphadadajuju** [comment]
Got it, thanks again for your clarification !
